Rails: Forms and Authentication
krys2fa/members-only pull request #1
Opened 2020-06-22 15:35 UTC by krys2fa

### Project: Members only

In this project, 
 - we created an exclusive a rails application where members can write posts about non-members.

2020-06-22 18:30 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi Team 👋 

You are doing a good job! In fact, you've met all the functional requirements! However there is one minor issue in your execution I could not overlook.

In posts/new route It is not clear which box the post is to be entered. Please fix it. the layout is really weird. I'd have expected the post to be the `textarea` field which I believe it is! 
![Screen Shot 2020-06-22 at 2 16 49 PM](https://user-images.githubusercontent.com/31193823/85322778-daf6fa80-b494-11ea-9bc5-969691fce669.png)

However, when I go to the home route I do not see the body of the post I only see the title. Please address this.

Other than this. Good job! 👏 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-22 18:30 UTC, mcrd25 commented on app/views/posts/index.html.erb
> +    <small><%= p.title %></small><br/>
I should also see the body

2020-06-23 10:33 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-06-23 11:05 UTC, krys2fa commented
Thanks @stratospherique.

2020-06-23 11:05 UTC, merged